### ISSUE TITLE
책 표지와 목차 관련 이슈

### ISSUE THREAD

**Issue by tlqaksqhr** [minoojjang/11-p1#1]
일단 gitbook 사이트 편집만으로는 표지를 생성하는게 불가합니다.
하지만, calibre와 gitbook-cli 프로그램을 이용해서 ebook(pdf) 형식으로 출판하는 경우 커버 그림을 추가 할 수 있습니다.

그리고 목차와 같은 경우 gitbook-cli로 ebook 생성시에 자동으로 생성되므로 따로 양식을 안만들어도 됩니다.

일단, 임시로 책 커버 이미지를 생성해서 업로드하였으므로 참고 바랍니다.
(pdf 파일은 카톡으로 공유해드리겠습니다.)

**Comment by minoojjang** [comment]
이제서야 봤네요
임시 커버 이미지는 목요일에 보내주셨던건가요?

**Comment by tlqaksqhr** [comment]
수요일날, 작업하면서 올렸었습니다.

**Comment by tlqaksqhr** [comment]
typora와 gitbook compile, pdf merge 서비스 등을 이용하여 PDF 변환 완료하였습니다.
